service: web-api

custom:
  serverless-offline:
    httpPort: 8888

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30

functions:
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: subscriber/{mysph_hash}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: subscriber/list
         method: get
         cors: true
 

plugins:
  - serverless-offline